# Generated by Django 3.1.6 on 2021-08-03 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_groups_grouptask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group_tasks',
            field=models.ManyToManyField(blank=True, null=True, related_name='group_tasks', to='todo.GroupTask'),
        ),
        migrations.AlterField(
            model_name='grouptask',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker', to=settings.AUTH_USER_MODEL),
        ),
    ]
