# Generated by Django 3.1.6 on 2021-08-04 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_groups_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
