# Generated by Django 3.1.6 on 2021-08-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20210804_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptask',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
