# Generated by Django 3.1.6 on 2021-08-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_grouptask_id_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptask',
            name='id_group',
        ),
    ]
