# Generated by Django 3.1.6 on 2021-08-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_remove_grouptask_id_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='login_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
