# Generated by Django 3.1.6 on 2021-08-31 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_profile_login_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group_tasks',
            field=models.ManyToManyField(blank=True, related_name='group_tasks', to='todo.GroupTask'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
